import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Layout from '../components/layout/layout';
import Header from '../components/header/header';

export default function Home() {
  return (
    <Layout className={styles.container}>
      <Head>
        <title>José Isaac</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}></main>

      <footer className={styles.footer}></footer>
    </Layout>
  );
}
