import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Layout from '../components/Layout/Layout';
import Header from '../components/Header/Header';
import SectionIntroduction from '../components/SectionIntroduction/SectionIntroduction';
import AboutMe from '../components/AboutMe/AboutMe';
import WhatDoIDo from '../components/WhatDoIDo/WhatDoIDo';

export default function Home() {
  return (
    <Layout className={styles.container}>
      <Head>
        <title>José Isaac</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </Head>

      <Header />

      <main className={styles.main}>
        <SectionIntroduction />
        <AboutMe />
        <WhatDoIDo />
      </main>

      <footer className={styles.footer}></footer>
    </Layout>
  );
}
